commit task 1, version 1.1
Pozitron64/CardName pull request #2
Opened 2022-05-18 23:33 UTC by Pozitron64

2022-05-19 02:45 UTC, snusmum requested changes

2022-05-19 02:45 UTC, snusmum commented on src/main/java/Main.java
>      private static String pathFail = "E:\\java_projects\\CardName\\src\\main\\resources\\fileAuthentication";
1. Значение не используется
2. Если бы использовалось, то нигде не отработало бы кроме твоего ПК. При работе с файлами проекта нужно использовать относительные пути.
3. Следует избегать глобальных переменных. В лучшем случае задавать константы.

2022-05-19 02:45 UTC, snusmum commented on src/main/java/Main.java
> +        pathFail = args[0];
Видимо имелось ввиду pathToFile | filePath. Сейчас название переменной ассоциируется с обработкой ошибки.

2022-05-19 02:45 UTC, snusmum commented on src/main/java/Main.java
>                      card.delete(0,card.length());
Вместо чистки можно было бы добавлять карточку в буфер, а для дальнейшей работы создавать новую.

2022-05-19 02:45 UTC, snusmum commented on src/test/java/MainTest.java
>          File file = new File("E:\\java_projects\\CardName\\src\\main\\resources\\fileAuthentication");
Тест падает из-за неизвестного пути.

2022-05-19 02:45 UTC, snusmum commented on src/main/java/Main.java
>          }
По заданию требовалось сортировать вывод.

2022-05-19 02:45 UTC, snusmum commented on src/main/java/Main.java
> +//                line.compareTo(new StringBuilder("")) == 0
Ненужный код надо удалять

2022-05-19 02:45 UTC, snusmum commented on src/test/java/MainTest.java
>                  actual.get(1).toString() + actual.get(0).toString());
Если на руках есть списки сущностей, то следует сравнивать их как сущности.
Если нет такой возможности, то тестовые данные можно было сразу собрать в одну строку.

2022-05-19 02:45 UTC, snusmum commented on src/test/java/MainTest.java
>          Assertions.assertEquals(expected.getFirstName(),actual.get(0).getFirstName());
Проверять нужно все поля. Тестовые инструменты позволяют сравнить объекты целиком, даже если у них не задан equals и hashCode.

2022-05-19 02:48 UTC, snusmum commented on src/main/java/Main.java
> +        if ((args.length < 1)||(args.length > 1)) {
if (args.length != 1)

2022-05-19 11:16 UTC, Pozitron64 commented on src/test/java/MainTest.java
>                  actual.get(1).toString() + actual.get(0).toString());
Залил новый коммит, долго просидел не смог найти нормального инструменты для сравнения объектов List<StringBulder>

2022-05-19 11:18 UTC, Pozitron64 commented on src/test/java/MainTest.java
>          Assertions.assertEquals(expected.getFirstName(),actual.get(0).getFirstName());
Также не смог понять как сравнить объекты нормально поэтому просто добавил метод equals() в Employee

2022-05-19 23:43 UTC, snusmum commented on src/test/java/MainTest.java
>          Assertions.assertEquals(expected.getFirstName(),actual.get(0).getFirstName());
Это хороший вариант.
Он не сработает только тогда, когда у объектов в сравнение для эффективности включаются не все поля.
Для проверок обычно используем AssertJ, в нём много удобных методов.
Сейчас менять нет необходимости.

2022-05-19 23:47 UTC, snusmum commented on src/test/java/MainTest.java
>                  actual.get(1).toString() + actual.get(0).toString());
Если бы StringBuilder реализовывал по содержимому, то можно было бы сравнить сами списки в assertEquals.
Мощные тулзы для проверок AssertJ или Hamcrest. Первый предпочтительнее.
В данном случае можно было бы из DataForTest возвращать список строк, а результат Main.read стримом мапить в список строк. Дальше ассертом уже сравнивать эти списки.
Но сейчас не обязательно.

2022-05-19 23:50 UTC, snusmum commented on src/test/java/MainTest.java
> +        File file = new File("src\\main\\resources\\fileAuthentication");
В подобной ситуации лучше использовать что-то вроде `new File(MainTest.class.getResource("fileAuthentication").getFile())`
Когда будет добавлен Sring появятся другие удобные методы для получения файлов из ресурсов.

2022-05-19 23:53 UTC, snusmum commented on src/test/java/MainTest.java
>      void correctParse() {
Тестам следует выделять блоки
// Arrange //Act //Assert

2022-05-20 00:23 UTC, snusmum approved these changes

2022-05-20 00:58 UTC, merged